alparse
=======

A python script for parsing the .c and .in files that is generated by Autolev
when a code dynamics() call is made.

The purpose of the parser is to get the essential code from the .c file so that
it may be used in other languages, and to help eliminate the tedious copying
and pasting that is often done when modifying the Autolev code to fit your
needs.

Currently, the goal is to support several types of output code:
1) Psuedo-code to be use in our Bicycle Dynamics Software
2) Python code
3) C code
4) C++ code

If Python or C++ code output is selected, it is optionally made into a class,
with class member functions for the relevant sections.
